config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'
  get 'my_page' => 'my_page#index'
  get 'my_page/draft' => 'reports#draft'
  get 'thanks' => 'my_page#thanks'
  get 'search' => 'searches#search'
  get 'age' => 'searches#all_age'
  get 'age/:value' => 'searches#age'
  get 'amh' => 'searches#all_amh'
  get 'amh/:value' => 'searches#amh'
  get 'status' => 'searches#all_status'
  get 'status/:value' => 'searches#status'
  get 'what_numbers' => 'searches#what_numbers'
  get 'what_number/:value' => 'searches#what_number'
  get 'search/clinics' => 'searches#clinics'

  get 'clinics_area' => 'searches#clinics_area'
  # get 'clinics_area/prefecture/:value' => 'searches#clinic_prefecture_area'
  get 'clinics_area/:prefecture' => 'clinics#prefecture'
  # get 'clinics_area/city/:value' => 'searches#clinic_city_area'
  get 'clinics_area/:prefecture/:value' => 'clinics#city'
  get 'tags' => 'searches#tags'
  get 'tags/:type/:value' => 'searches#tag'

  get 'count' => 'searches#count'
  get 'count/:type/:value' => 'searches#sairan_ishoku_count'
  get 'cycletype' => 'searches#cycletype'
  get 'cycletype/:type/:value' => 'searches#cycletype_sairan_ishoku'
  get 'grade' => 'searches#grade'
  get 'grade/:type/:value' => 'searches#embryo_grade'
  get 'works' => 'searches#works'
  get 'work/:value' => 'searches#work'
  get 'works_switch' => 'searches#works_switch'
  get 'work_switch/:value' => 'searches#work_switch'
  get 'costs' => 'searches#costs'
  get 'cost/:value' => 'searches#cost'
  get 'about' => 'application#about'
  get 'terms' => 'application#terms'
  get 'privacy' => 'application#privacy'
  get 'guideline' => 'application#guideline'
  get 'repoco' => 'application#repoco'
  get 'terminology' => 'application#terminology'
  get 'faq' => 'application#faq'
  get 'make' => 'application#make'
  get 'hack' => 'application#hack'
  get 'statistic' => 'application#statistic'

  devise_for :users, path: '', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }

  # ゲストログイン機能(参考: https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104)
  # devise_scope :user do
    # post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  # end
  # ここまで(ゲストログイン機能)

  resources :users
    put "/users/:id/hide" => "users#hide", as: 'users_hide'

    # centerの各レポコ中央部のuserの住まい,(prefecture, city)のリンク↓
    get 'users_area' => 'users#all_area'
    get 'users_/:prefecture' => 'users#area_prefecture'
    get 'users_/:prefecture/:city' => 'users#area_city'
    get "cities_select_area" => "users#cities_select_area"
    # ここまで

  resources :users, shallow: true do
    resources :reports, only: %[index]
  end

  resources :reports do
    collection do
      post :confirm
      get 'search'
    end
    member do
      patch :confirm
      patch :release
      patch :nonrelease
    end
    resource :likes, only: [:create, :destroy]
  end

  resources :clinics

  # centerの各レポコ下部のclinic, prefecture, cityのリンク↓
  get 'clinic/:value' => 'clinics#clinic_report'
  get 'clinics/region/:region' => 'clinics#region'
  get 'clinics_/:prefecture' => 'clinics#prefecture'
  get 'clinics/:prefecture/:value' => 'clinics#city'
  get 'search_cl' => 'clinics#search_cl'
  # ここまで

  # formでも利用
  get "cities_select" => "searches#cities_select_clinics"
  get "clinics_select" => "searches#clinics_select"
  # ここまで

  get "clinic_select" => "searches#clinic_select"

  get "address_cities_select" => "reports#address_cities_select"

  resources :comments, only: %i[create destroy]

  resources :notifications, only: :index

  namespace :admin do
    resources :users
    resources :reports
    resources :clinics
    root 'admin#home'
  end

  get "signup" => "reports#signup"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        reports#index
#                               my_page GET    /my_page(.:format)                                                                       my_page#index
#                         my_page_draft GET    /my_page/draft(.:format)                                                                 reports#draft
#                                thanks GET    /thanks(.:format)                                                                        my_page#thanks
#                                search GET    /search(.:format)                                                                        searches#search
#                                   age GET    /age(.:format)                                                                           searches#all_age
#                                       GET    /age/:value(.:format)                                                                    searches#age
#                                   amh GET    /amh(.:format)                                                                           searches#all_amh
#                                       GET    /amh/:value(.:format)                                                                    searches#amh
#                                status GET    /status(.:format)                                                                        searches#all_status
#                                       GET    /status/:value(.:format)                                                                 searches#status
#                        search_clinics GET    /search/clinics(.:format)                                                                searches#clinics
#                 category_clinics_area GET    /category/clinics_area(.:format)                                                         searches#clinics_area
#                                       GET    /category/clinics_area/prefecture/:value(.:format)                                       searches#clinic_prefecture_area
#                                       GET    /category/clinics_area/city/:value(.:format)                                             searches#clinic_city_area
#                         category_tags GET    /category/tags(.:format)                                                                 searches#tags
#                                       GET    /:category/:tags/:gender/:value(.:format)                                                searches#tag
#                                 works GET    /works(.:format)                                                                         searches#works
#                                       GET    /work/:value(.:format)                                                                   searches#work
#                                 costs GET    /costs(.:format)                                                                         searches#costs
#                                       GET    /cost/:value(.:format)                                                                   searches#cost
#                                 about GET    /about(.:format)                                                                         application#about
#                                 terms GET    /terms(.:format)                                                                         application#terms
#                               privacy GET    /privacy(.:format)                                                                       application#privacy
#                             guideline GET    /guideline(.:format)                                                                     application#guideline
#                                repoco GET    /repoco(.:format)                                                                        application#repoco
#                           terminology GET    /terminology(.:format)                                                                   application#terminology
#                                   faq GET    /faq(.:format)                                                                           application#faq
#                                  make GET    /make(.:format)                                                                          application#make
#                                  hack GET    /hack(.:format)                                                                          application#hack
#                             statistic GET    /statistic(.:format)                                                                     application#statistic
#                      new_user_session GET    /sign_in(.:format)                                                                       users/sessions#new
#                          user_session POST   /sign_in(.:format)                                                                       users/sessions#create
#                  destroy_user_session DELETE /sign_out(.:format)                                                                      users/sessions#destroy
#                     new_user_password GET    /password/new(.:format)                                                                  users/passwords#new
#                    edit_user_password GET    /password/edit(.:format)                                                                 users/passwords#edit
#                         user_password PATCH  /password(.:format)                                                                      users/passwords#update
#                                       PUT    /password(.:format)                                                                      users/passwords#update

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::ApplicationController
  def show
    @report = Report.find(params[:id])
    
    @clinics = @report.itinerary_of_choosing_a_clinics.order(order_of_transfer: "desc")
    @clinics_exist = @clinics.map { |i| i[:clinic_id] }

    @unsuccessful_sairan_cycles = @report.unsuccessful_sairan_cycles.order(un_sairan_number: "asc")
    @unsuccessful_ishoku_cycles = @report.unsuccessful_ishoku_cycles.order(un_ishoku_number: "asc")

    @special_inspection_era = @report.special_inspections.where(name: 1)
    @special_inspection_emma = @report.special_inspections.where(name: 2)
    @special_inspection_alice = @report.special_inspections.where(name: 3)
    @special_inspection_trio = @report.special_inspections.where(name: 4)
    @special_inspection_erpeak = @report.special_inspections.where(name: 5)
    @special_inspection_hysteroscopy = @report.special_inspections.where(name: 6)
    @special_inspection_intrauterine_flora = @report.special_inspections.where(name: 7)
    @special_inspection_endometrial_biopsy = @report.special_inspections.where(name: 8)
    @special_inspection_hidukeshin = @report.special_inspections.where(name: 9)
    @special_inspection_bce = @report.special_inspections.where(name: 10)
    @special_inspection_chromosome = @report.special_inspections.where(name: 11)
    @special_inspection_ca125 = @report.special_inspections.where(name: 12)
    @special_inspection_mri = @report.special_inspections.where(name: 13)
    @special_inspection_vitamin_d = @report.special_inspections.where(name: 14)
    @special_inspection_copper_zinc = @report.special_inspections.where(name: 15)
    @special_inspection_kruger = @report.special_inspections.where(name: 16)
    @special_inspection_dfi = @report.special_inspections.where(name: 17)
    @special_inspection_pgta = @report.special_inspections.where(name: 18)
    @special_inspection_other_inspection = @report.special_inspections.where(name: 99)

    gon.clinic_name = @report.clinic.name
    gon.clinic_evaluation = []
    gon.clinic_evaluation << @report.doctor_quality << @report.staff_quality << @report.impression_of_technology << @report.impression_of_price << @report.average_waiting_time2 << @report.comfort_of_space
    @clinic_evaluation = gon.clinic_evaluation.compact

    if @report.doctor_quality.blank?
      @report.doctor_quality = 0
    end
    if @report.staff_quality.blank?
      @report.staff_quality = 0
    end
    if @report.impression_of_technology.blank?
      @report.impression_of_technology = 0
    end
    if @report.impression_of_price.blank?
      @report.impression_of_price = 0
    end
    if @report.average_waiting_time2.blank?
      @report.average_waiting_time2 = 0
    end
    if @report.comfort_of_space.blank?
      @report.comfort_of_space = 0
    end
    @average_score = ((@report.doctor_quality + @report.staff_quality + @report.impression_of_technology + @report.impression_of_price + @report.average_waiting_time2 + @report.comfort_of_space)/6.to_f).round(1)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/_right.html.erb
<div class="sticky-area px-0 py-3">
<% if false %>
<form action="https://docs.google.com/forms/u/2/d/e/1FAIpQLSdSe_vOEPPdpsZI0Wn5YuYUl7LTqaYeq8x_yBLGaOhiM4eiuQ/formResponse" target="_self" method="POST" class="text-right">
  <textarea class="feedback-textarea" rows="7" placeholder="REPOCOに関するご意見やご要望をお聞かせください。どんな些細なことでもウェルカムです！" name="entry.1597222762" required></textarea><br>
  <button type="submit" class="btn btn-outline-primary feedback-sidebar">意見を送る&nbsp;<i data-feather="send" class="feather-icon-style1"></i></button>
</form>
<% end %>
<% if user_signed_in? %>
  <% if current_user.registration_status1 || current_user.registration_status2 == true %>
    <div class="sidebar_promote_item mt-3">
      <div class="sidebar_promote_card">
        <div class="sidebar_promote_card_header row">
          <div class="col-2 sidebar_promote_card_header_left">
            <i data-feather="settings" class="pl-1" style="color: #646262"></i>
          </div>
          <div class="col-10 sidebar_promote_card_header_right">
            <% if request.path.include?("reports") %>
              <p>簡単に設定できる治療歴＆プロフィール設定はお済みですか？</p>
            <% else %>
              <p>まずは治療歴＆プロフィール設定をしましょう！<br><span class="text-muted small">（こちらで設定した「治療情報」は投稿したレポコにも反映されます）</span></p>
            <% end %>
          </div>
        </div>
        <div class="sidebar_promote_card_body">
          <%= link_to edit_user_registration_path, { title: "治療歴を設定する", style: "text-decoration: none;" } do %>
            <button class="green_btn">設定する</button>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="sidebar_promote_item mt-3">
    <div class="sidebar_promote_card">
      <div class="sidebar_promote_card_header row">
        <div class="col-2 sidebar_promote_card_header_left">
          <i data-feather="heart" class="pl-1" style="color: #646262"></i>
        </div>
        <div class="col-10 sidebar_promote_card_header_right">
          <p>参考になるレポコをいつでも読み返せるストック機能を利用するには&nbsp;<%= link_to "ユーザー登録", new_user_registration_path %>&nbsp;または&nbsp;<%= link_to "ログイン", new_user_session_path %>&nbsp;が必要です。ユーザー登録はこちらから10秒ほどで簡単に登録できます <i data-feather="arrow-down" class="px-1" style="color: #646262"></i></p>
        </div>
      </div>
      <div class="sidebar_promote_card_body">
        <%= link_to new_user_registration_path, { title: "ユーザー登録をする", style: "text-decoration: none;" } do %>
          <button class="green_btn">新規登録</button>
        <% end %>
        <%= link_to new_user_session_path, { title: "ログイン", style: "text-decoration: none;" } do %>
          <button class="outline_green_btn mt-3">登録済みの方はこちら</button>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="sidebar_promote_item mt-4">
  <div class="sidebar_promote_card">
    <div class="sidebar_promote_card_header row">
      <div class="col-2 sidebar_promote_card_header_left">
        <i data-feather="book" class="pl-1" style="color: #646262"></i>
      </div>
      <div class="col-10 sidebar_promote_card_header_right mt-1">
        <p class="mb-0 font-weight-bold"><%= link_to "用語", terminology_path %></p>
      </div>
    </div>
  </div>
</div>

<div class="sidebar_rank_report mt-5">
  <% if Report.rank.present? %>
    <div class="mb-2">
      <i data-feather="trending-up" class="pr-1 text-dark"></i>&nbsp;&nbsp;<h7 class="font-weight-bold text-dark">注目レポコ</h7>
    </div>
    <% Report.rank.each do |report| %>
      <%= link_to report_path(report), data: { "turbolinks" => false }, style:"text-decoration: none;" do %>
        <div class="mb-2">
          <div class="row mb-2 rounded-lg">
            <div class="col-9 pt-2 pr-2">
              <div class="mb-3 text-dark d-flex align-items-center" style="height: 60px">
                <p class="mb-0">
                <% if report.title.present? %>
                  <small class="text-muted" style="font-size: 5px;"><%= report.clinic.name %>&nbsp;(<%= report.clinic.prefecture.name %>)</small>
                  <br><span style="font-size: 14px;"><%= strip_tags(report.title.to_s).gsub(/[\n]/,"").strip.truncate(26) %></span>
                <% else %>
                  <% if report.year_of_treatment_end.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.year_of_treatment_end.year %>年卒業</small>
                  <% end %>
                  <% if report.fertility_treatment_number.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.str_fertility_treatment_number %></small>
                  <% end %>
                  <% if report.current_state.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.str_current_state %></small>
                  <% end %>
                  <br><span style="font-size: 14px;"><%= report.clinic.name %><span class="text-muted" style="font-size: 5px;">(<%= report.clinic.prefecture.name %>)</span>でのレポコ</span>
                <% end %>
                </p>
              </div>
              <div class="small pb-2">
                <% if user_signed_in? %>
                  <p class="float-left mb-0 pr-2 d-inline" style="font-size:10px">
                    <% if current_user.already_liked?(report) %>
                      <%= images_action_svg("like_mobile.svg") %><span class="text-danger">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                    <% else %>
                      <%= images_action_svg("unlike_mobile.svg") %><span class="text-muted">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                    <% end %>
                  </p>
                <% else %>
                  <p class="float-left mb-0 pr-2 d-inline" style="font-size:10px">
                    <%= images_action_svg("unlike_mobile.svg") %><span class="text-muted">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                  </p>
                <% end %>
                <p class="m-0 text-muted d-flex align-items-center">
                  <span class="small"><%= report.prefecture.name %></span>&nbsp;
                  <% if report.str_treatment_end_age.present? %>
                    <span class="small"><%= report.str_treatment_end_age %></span>&nbsp;
                  <% end %>
                  <%= strip_tags(report.user.name.to_s).gsub(/[\n]/,"").strip.truncate(8) %>
                </p>
              </div>
            </div>
            <div class="col-3 py-2 pl-0 d-flex align-items-center">
              <% if report.user.icon.attached? %>
                <%= image_tag(report.user.icon, alt: "icon", class: "icon_image2", loading: "lazy") %>
              <% else %>
                <% if report.treatment_end_age == nil %>
                  <%= image_tag("icon/g_blank.png", alt: "generation_blank", class: "icon_image2_border", loading: "lazy", title: "不明") %>
                <% elsif report.treatment_end_age < 25 %>
                  <%= image_tag("icon/g_10_24.png", alt: "generation10_24", class: "icon_image2_border", loading: "lazy", title: "〜24歳") %>
                <% elsif report.treatment_end_age < 30 %>
                  <%= image_tag("icon/g_25_29.png", alt: "generation25_29", class: "icon_image2_border", loading: "lazy", title: "25〜29歳") %>
                <% elsif report.treatment_end_age < 35 %>
                  <%= image_tag("icon/g_30_34.png", alt: "generation30_34", class: "icon_image2_border", loading: "lazy", title: "30〜34歳") %>
                <% elsif report.treatment_end_age < 40 %>
                  <%= image_tag("icon/g_35_39.png", alt: "generation35_39", class: "icon_image2_border", loading: "lazy", title: "35〜39歳") %>
                <% elsif report.treatment_end_age < 45 %>
                  <%= image_tag("icon/g_40_44.png", alt: "generation40_44", class: "icon_image2_border", loading: "lazy", title: "40〜44歳") %>
                <% else %>
                  <%= image_tag("icon/g_45_.png", alt: "generation45_", class: "icon_image2_border", loading: "lazy", title: "45歳〜") %>
                <% end %>
              <% end %>
            </div>
          </div><hr class="my-2">
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>
</div>

app/views/admin/reports/_show_right.html.erb
<% if Report.same_cl(@report).present? %>
  <div class="sidebar_same_cl_report mt-5">
    <div class="mb-2">
      <i data-feather="layers" class="pr-1 text-dark"></i>&nbsp;&nbsp;<h7 class="font-weight-bold text-dark">同じクリニックのレポコ</h7>
    </div>
    <% Report.same_cl(@report).each do |report| %>
      <%= link_to report_path(report), data: { "turbolinks" => false }, style:"text-decoration: none;" do %>
        <div class="mb-2">
          <div class="row mb-2 rounded-lg">
            <div class="col-9 pt-2 pr-2">
              <div class="mb-3 text-dark d-flex align-items-center" style="height: 60px">
                <p class="mb-0">
                <% if report.title.present? %>
                  <small class="text-muted" style="font-size: 5px;"><%= report.clinic.name %>&nbsp;(<%= report.clinic.prefecture.name %>)</small>
                  <br><span style="font-size: 14px;"><%= strip_tags(report.title.to_s).gsub(/[\n]/,"").strip.truncate(26) %></span>
                <% else %>
                  <% if report.year_of_treatment_end.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.year_of_treatment_end.year %>年卒業</small>
                  <% end %>
                  <% if report.fertility_treatment_number.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.str_fertility_treatment_number %></small>
                  <% end %>
                  <% if report.current_state.present? %>
                    <small class="text-muted" style="font-size: 5px;"><%= report.str_current_state %></small>
                  <% end %>
                  <br><span style="font-size: 14px;"><%= report.clinic.name %><span class="text-muted" style="font-size: 5px;">(<%= report.clinic.prefecture.name %>)</span>でのレポコ</span>
                <% end %>
                </p>
              </div>
              <div class="small pb-2">
                <% if user_signed_in? %>
                  <p class="float-left mb-0 pr-2 d-inline" style="font-size:10px">
                    <% if current_user.already_liked?(report) %>
                      <%= images_action_svg("like_mobile.svg") %><span class="text-danger">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                    <% else %>
                      <%= images_action_svg("unlike_mobile.svg") %><span class="text-muted">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                    <% end %>
                  </p>
                <% else %>
                  <p class="float-left mb-0 pr-2 d-inline" style="font-size:10px">
                    <%= images_action_svg("unlike_mobile.svg") %><span class="text-muted">&nbsp;&nbsp;<% if report.likes.present? %><%= report.likes.count %><% end %></span>
                  </p>
                <% end %>
                <p class="m-0 text-muted d-flex align-items-center">
                  <span class="small"><%= report.prefecture.name %></span>&nbsp;
                  <% if report.str_treatment_end_age.present? %>
                    <span class="small"><%= report.str_treatment_end_age %></span>&nbsp;
                  <% end %>
                  <%= strip_tags(report.user.name.to_s).gsub(/[\n]/,"").strip.truncate(8) %>
                </p>
              </div>
            </div>
            <div class="col-3 py-2 pl-0 d-flex align-items-center">
              <% if report.user.icon.attached? %>
                <%= image_tag(report.user.icon, alt: "icon", class: "icon_image2", loading: "lazy") %>
              <% else %>
                <% if report.treatment_end_age == nil %>
                  <%= image_tag("icon/g_blank.png", alt: "generation_blank", class: "icon_image2_border", loading: "lazy", title: "不明") %>
                <% elsif report.treatment_end_age < 25 %>
                  <%= image_tag("icon/g_10_24.png", alt: "generation10_24", class: "icon_image2_border", loading: "lazy", title: "〜24歳") %>
                <% elsif report.treatment_end_age < 30 %>
                  <%= image_tag("icon/g_25_29.png", alt: "generation25_29", class: "icon_image2_border", loading: "lazy", title: "25〜29歳") %>
                <% elsif report.treatment_end_age < 35 %>
                  <%= image_tag("icon/g_30_34.png", alt: "generation30_34", class: "icon_image2_border", loading: "lazy", title: "30〜34歳") %>
                <% elsif report.treatment_end_age < 40 %>
                  <%= image_tag("icon/g_35_39.png", alt: "generation35_39", class: "icon_image2_border", loading: "lazy", title: "35〜39歳") %>
                <% elsif report.treatment_end_age < 45 %>
                  <%= image_tag("icon/g_40_44.png", alt: "generation40_44", class: "icon_image2_border", loading: "lazy", title: "40〜44歳") %>
                <% else %>
                  <%= image_tag("icon/g_45_.png", alt: "generation45_", class: "icon_image2_border", loading: "lazy", title: "45歳〜") %>
                <% end %>
              <% end %>
            </div>
          </div><hr class="my-2">
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>