config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'
  get 'my_page' => 'my_page#index'
  get 'my_page/draft' => 'reports#draft'
  get 'thanks' => 'my_page#thanks'
  get 'search' => 'searches#search'
  get 'age' => 'searches#all_age'
  get 'age/:value' => 'searches#age'
  get 'amh' => 'searches#all_amh'
  get 'amh/:value' => 'searches#amh'
  get 'status' => 'searches#all_status'
  get 'status/:value' => 'searches#status'
  get 'what_numbers' => 'searches#what_numbers'
  get 'what_number/:value' => 'searches#what_number'
  get 'search/clinics' => 'searches#clinics'

  get 'clinics_area' => 'searches#clinics_area'
  # get 'clinics_area/prefecture/:value' => 'searches#clinic_prefecture_area'
  get 'clinics_area/:prefecture' => 'clinics#prefecture'
  # get 'clinics_area/city/:value' => 'searches#clinic_city_area'
  get 'clinics_area/:prefecture/:value' => 'clinics#city'
  get 'tags' => 'searches#tags'
  get 'tags/:type/:value' => 'searches#tag'

  get 'count' => 'searches#count'
  get 'count/:type/:value' => 'searches#sairan_ishoku_count'
  get 'cycletype' => 'searches#cycletype'
  get 'cycletype/:type/:value' => 'searches#cycletype_sairan_ishoku'
  get 'grade' => 'searches#grade'
  get 'grade/:type/:value' => 'searches#embryo_grade'
  get 'works' => 'searches#works'
  get 'work/:value' => 'searches#work'
  get 'works_switch' => 'searches#works_switch'
  get 'work_switch/:value' => 'searches#work_switch'
  get 'costs' => 'searches#costs'
  get 'cost/:value' => 'searches#cost'
  get 'about' => 'application#about'
  get 'terms' => 'application#terms'
  get 'privacy' => 'application#privacy'
  get 'guideline' => 'application#guideline'
  get 'repoco' => 'application#repoco'
  get 'terminology' => 'application#terminology'
  get 'faq' => 'application#faq'
  get 'make' => 'application#make'
  get 'hack' => 'application#hack'
  get 'statistic' => 'application#statistic'

  devise_for :users, path: '', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }

  # ゲストログイン機能(参考: https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104)
  # devise_scope :user do
    # post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  # end
  # ここまで(ゲストログイン機能)

  resources :users
    put "/users/:id/hide" => "users#hide", as: 'users_hide'

    # centerの各レポコ中央部のuserの住まい,(prefecture, city)のリンク↓
    get 'users_area' => 'users#all_area'
    get 'users_/:prefecture' => 'users#area_prefecture'
    get 'users_/:prefecture/:city' => 'users#area_city'
    get "cities_select_area" => "users#cities_select_area"
    # ここまで

  resources :users, shallow: true do
    resources :reports, only: %[index]
  end

  resources :reports do
    collection do
      post :confirm
      get 'search'
    end
    member do
      patch :confirm
      patch :release
      patch :nonrelease
    end
    resource :likes, only: [:create, :destroy]
  end

  resources :clinics

  # centerの各レポコ下部のclinic, prefecture, cityのリンク↓
  get 'clinic/:value' => 'clinics#clinic_report'
  get 'clinics/region/:region' => 'clinics#region'
  get 'clinics_/:prefecture' => 'clinics#prefecture'
  get 'clinics/:prefecture/:value' => 'clinics#city'
  get 'search_cl' => 'clinics#search_cl'
  # ここまで

  # formでも利用
  get "cities_select" => "searches#cities_select_clinics"
  get "clinics_select" => "searches#clinics_select"
  # ここまで

  get "clinic_select" => "searches#clinic_select"

  get "address_cities_select" => "reports#address_cities_select"

  resources :comments, only: %i[create destroy]

  resources :notifications, only: :index

  namespace :admin do
    resources :users
    resources :reports
    resources :clinics
    root 'admin#home'
  end

  get "signup" => "reports#signup"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        reports#index
#                               my_page GET    /my_page(.:format)                                                                       my_page#index
#                         my_page_draft GET    /my_page/draft(.:format)                                                                 reports#draft
#                                thanks GET    /thanks(.:format)                                                                        my_page#thanks
#                                search GET    /search(.:format)                                                                        searches#search
#                                   age GET    /age(.:format)                                                                           searches#all_age
#                                       GET    /age/:value(.:format)                                                                    searches#age
#                                   amh GET    /amh(.:format)                                                                           searches#all_amh
#                                       GET    /amh/:value(.:format)                                                                    searches#amh
#                                status GET    /status(.:format)                                                                        searches#all_status
#                                       GET    /status/:value(.:format)                                                                 searches#status
#                        search_clinics GET    /search/clinics(.:format)                                                                searches#clinics
#                 category_clinics_area GET    /category/clinics_area(.:format)                                                         searches#clinics_area
#                                       GET    /category/clinics_area/prefecture/:value(.:format)                                       searches#clinic_prefecture_area
#                                       GET    /category/clinics_area/city/:value(.:format)                                             searches#clinic_city_area
#                         category_tags GET    /category/tags(.:format)                                                                 searches#tags
#                                       GET    /:category/:tags/:gender/:value(.:format)                                                searches#tag
#                                 works GET    /works(.:format)                                                                         searches#works
#                                       GET    /work/:value(.:format)                                                                   searches#work
#                                 costs GET    /costs(.:format)                                                                         searches#costs
#                                       GET    /cost/:value(.:format)                                                                   searches#cost
#                                 about GET    /about(.:format)                                                                         application#about
#                                 terms GET    /terms(.:format)                                                                         application#terms
#                               privacy GET    /privacy(.:format)                                                                       application#privacy
#                             guideline GET    /guideline(.:format)                                                                     application#guideline
#                                repoco GET    /repoco(.:format)                                                                        application#repoco
#                           terminology GET    /terminology(.:format)                                                                   application#terminology
#                                   faq GET    /faq(.:format)                                                                           application#faq
#                                  make GET    /make(.:format)                                                                          application#make
#                                  hack GET    /hack(.:format)                                                                          application#hack
#                             statistic GET    /statistic(.:format)                                                                     application#statistic
#                      new_user_session GET    /sign_in(.:format)                                                                       users/sessions#new
#                          user_session POST   /sign_in(.:format)                                                                       users/sessions#create
#                  destroy_user_session DELETE /sign_out(.:format)                                                                      users/sessions#destroy
#                     new_user_password GET    /password/new(.:format)                                                                  users/passwords#new
#                    edit_user_password GET    /password/edit(.:format)                                                                 users/passwords#edit
#                         user_password PATCH  /password(.:format)                                                                      users/passwords#update
#                                       PUT    /password(.:format)                                                                      users/passwords#update

app/views/admin/admin/home.html.erb
<div class="row my-0 py-2 px-0 text-center alert alert-info d-flex align-items-center">
  <div class="col-sm-3">
    <%= link_to root_path do%><h6 class="mb-0 text-dark">REPOCO</h6><% end %>
  </div>
  <div class="d-none d-sm-block col-sm-3">
    <small class="text-muted">レポコ</small>
    <h6 class="mb-0"><%= @reports.size %>投稿</h6>
    <p class="mb-0 small">公&nbsp;<%= @released_reports.size %>&nbsp;(非&nbsp;<%= @reports.size - @released_reports.size %>)</p>
  </div>
  <div class="d-none d-sm-block col-sm-3">
    <small class="text-muted">ユーザー数</small>
    <h6 class="mb-0"><%= @users.size %>人</h6>
  </div>
  <div class="d-none d-sm-block col-sm-3">
    <small class="text-muted">クリニック数</small>
    <h6 class="mb-0"><%= @clinics.size.to_s(:delimited) %>施設</h6>
    <p class="mb-0 small">(<%= @clinics_count_released.size %>/<%= @clinics_count.size %>施設)</p>
  </div>
</div>
<ul class="d-block d-sm-none nav nav-tabs d-flex justify-content-between mb-3 sticky-top">
  <li class="nav-item"><a class="list-group-item list-group-item-action active" data-toggle="list" href="#list-dashboard" role="tab">Dashboard</a></li>
  <li class="nav-item"><a class="list-group-item list-group-item-action" data-toggle="list" href="#list-repoco" role="tab">REPOCO</a></li>
  <li class="nav-item"><a class="list-group-item list-group-item-action" data-toggle="list" href="#list-users" role="tab">Users</a></li>
  <li class="nav-item"><a class="list-group-item list-group-item-action" data-toggle="list" href="#list-clinics" role="tab">Clinics</a></li>
</ul>
<div class="row px-1">
  <div class="d-none d-sm-block col-sm-2 dashboard-left pr-0">
    <div class="list-group py-0" id="admin-list" role="tablist">
      <a class="list-group-item list-group-item-action active" data-toggle="list" href="#list-dashboard" role="tab">Dashboard</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-repoco" role="tab">REPOCO</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-users" role="tab">Users</a>
      <a class="list-group-item list-group-item-action" data-toggle="list" href="#list-clinics" role="tab">Clinics</a>
    </div>
  </div>
  <div class="col-sm-10 dashboard-main">
    <div class="tab-content pt-3" id="nav-admin-tabContent">
      <div class="tab-pane active" id="list-dashboard" role="tabpanel">
        <div class="row px-1">
          <div class="col-4 pb-3 text-center">
            <small class="text-muted">投稿</small>
            <h5 class="mb-0"><%= @reports.size %>件</h5>
            <p class="mb-0 small">(<%= @released_reports.size %>投稿)</p>
          </div>
          <div class="col-4 pb-3 text-center">
            <small class="text-muted">ユーザー</small>
            <h5><%= @users.size %>人</h5>
          </div>
          <div class="col-4 pb-3 text-center">
            <small class="text-muted">クリニック</small>
            <h5 class="mb-0"><%= @clinics.size.to_s(:delimited) %>施設</h5>
            <p class="mb-0 small">(<%= @clinics_count_released.size %>/<%= @clinics_count.size %>施設)</p>
          </div>
        </div>
        <div class="tab-wrap1 mt-3 px-1">
          <input id="TAB-01" type="radio" name="TAB" class="tab-switch" checked="checked"/><label class="tab-label" for="TAB-01">レポコ</label>
          <div class="tab-content1">
          </div>
          <input id="TAB-02" type="radio" name="TAB" class="tab-switch"/><label class="tab-label" for="TAB-02">ユーザー</label>
          <div class="tab-content1">
          </div>
          <input id="TAB-03" type="radio" name="TAB" class="tab-switch"/><label class="tab-label" for="TAB-03">クリニック</label>
          <div class="tab-content1">
          </div>
        </div>
      </div>
      <div class="tab-pane" id="list-repoco" role="tabpanel">
        <table class="table table-sm small">
          <thead>
            <tr>
              <th scope="col">St</th>
              <th scope="col">CL</th>
              <th scope="col">NM</th>
              <th scope="col" class="d-none d-sm-table-cell">CS</th>
              <th scope="col" class="d-none d-sm-table-cell">Age</th>
              <th scope="col" class="d-none d-sm-table-cell">GY</th>
              <th scope="col">PT</th>
              <th scope="col" class="d-none d-md-table-cell">Ud</th>
              <th scope="col">LK</th>
            </tr>
          </thead>
          <tbody>
            <% @reports.each do |report| %>
              <tr>
                <td>
                  <% if report.status == "nonreleased" %>
                    <span class="badge badge-danger">非</span>
                  <% end %>
                </td>
                <td><%= strip_tags(report.clinic.name).gsub(/[\n]/,"").strip.truncate(15) %></td>
                <td><%= strip_tags(report.user.name).gsub(/[\n]/,"").strip.truncate(10) %></td>
                <td class="d-none d-sm-table-cell"><%= report.str_current_state %></td>
                <td class="d-none d-sm-table-cell"><%= report.str_treatment_end_age %></td>
                <td class="d-none d-sm-table-cell">
                  <% if report.year_of_treatment_end.present? %>
                    <%= report.year_of_treatment_end.year %>年卒
                  <% end %>
                </td>
                <td>
                  <%= report.created_at.to_s(:datetime_jp) %>
                </td>
                <td class="d-none d-md-table-cell">
                  <%= report.updated_at.to_s(:datetime_jp) %>
                </td>
                <td>
                  <%= link_to admin_report_path(report), data: { "turbolinks" => false } do %><i data-feather="external-link" class="p-1"></i><% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane" id="list-users" role="tabpanel">
        <table class="table table-sm small">
          <thead>
            <tr>
              <th scope="col">NM</th>
              <th scope="col">Age</th>
              <th scope="col">PF</th>
              <th scope="col">RP</th>
              <th scope="col">LK</th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= strip_tags(user.name).gsub(/[\n]/,"").strip.truncate(10) %></td>
                <td>
                  <% if user.birthday.blank? %>
                    <span class="text-danger small">未設定</span>
                  <% else %>
                    <% birthday = (user.birthday.to_s).delete("^0-9") %>
                    <%= (Date.today.strftime('%Y%m%d').to_i - birthday[0..7].to_i) / 10000 %>歳
                  <% end %>
                </td>
                <td>
                  <% if user.self_introduction.present? %>
                    <%= strip_tags(user.self_introduction).gsub(/[\n]/,"").strip.truncate(15) %>
                  <% end %>
                </td>
                <td>
                  <%= user.reports.size %>件
                </td>
                <td>
                  <%= link_to admin_user_path(user) do %><i data-feather="external-link" class="p-1"></i><% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane" id="list-clinics" role="tabpanel">
        <table class="table table-sm small">
          <thead>
            <tr>
              <th scope="col">NM</th>
              <th scope="col">PF</th>
              <th scope="col">CT</th>
              <th scope="col">RP</th>
            </tr>
          </thead>
          <tbody>
          <% @clinics_reports.each do |clinic| %>
            <tr>
              <td>
                <%= clinic.name %>
              </td>
              <td>
                <%= clinic.prefecture.name %>
              </td>
              <td>
                <%= clinic.city.name %>
              </td>
              <td>
                <%= clinic.reports.size %>件
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>