config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'
  get 'my_page' => 'my_page#index'
  get 'my_page/draft' => 'reports#draft'
  get 'thanks' => 'my_page#thanks'
  get 'search' => 'searches#search'
  get 'age' => 'searches#all_age'
  get 'age/:value' => 'searches#age'
  get 'amh' => 'searches#all_amh'
  get 'amh/:value' => 'searches#amh'
  get 'status' => 'searches#all_status'
  get 'status/:value' => 'searches#status'
  get 'what_numbers' => 'searches#what_numbers'
  get 'what_number/:value' => 'searches#what_number'
  get 'search/clinics' => 'searches#clinics'

  get 'clinics_area' => 'searches#clinics_area'
  # get 'clinics_area/prefecture/:value' => 'searches#clinic_prefecture_area'
  get 'clinics_area/:prefecture' => 'clinics#prefecture'
  # get 'clinics_area/city/:value' => 'searches#clinic_city_area'
  get 'clinics_area/:prefecture/:value' => 'clinics#city'
  get 'tags' => 'searches#tags'
  get 'tags/:type/:value' => 'searches#tag'

  get 'count' => 'searches#count'
  get 'count/:type/:value' => 'searches#sairan_ishoku_count'
  get 'cycletype' => 'searches#cycletype'
  get 'cycletype/:type/:value' => 'searches#cycletype_sairan_ishoku'
  get 'grade' => 'searches#grade'
  get 'grade/:type/:value' => 'searches#embryo_grade'
  get 'works' => 'searches#works'
  get 'work/:value' => 'searches#work'
  get 'works_switch' => 'searches#works_switch'
  get 'work_switch/:value' => 'searches#work_switch'
  get 'costs' => 'searches#costs'
  get 'cost/:value' => 'searches#cost'
  get 'about' => 'application#about'
  get 'terms' => 'application#terms'
  get 'privacy' => 'application#privacy'
  get 'guideline' => 'application#guideline'
  get 'repoco' => 'application#repoco'
  get 'terminology' => 'application#terminology'
  get 'faq' => 'application#faq'
  get 'make' => 'application#make'
  get 'hack' => 'application#hack'
  get 'statistic' => 'application#statistic'

  devise_for :users, path: '', controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }

  # ゲストログイン機能(参考: https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104)
  # devise_scope :user do
    # post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  # end
  # ここまで(ゲストログイン機能)

  resources :users
    put "/users/:id/hide" => "users#hide", as: 'users_hide'

    # centerの各レポコ中央部のuserの住まい,(prefecture, city)のリンク↓
    get 'users_area' => 'users#all_area'
    get 'users_/:prefecture' => 'users#area_prefecture'
    get 'users_/:prefecture/:city' => 'users#area_city'
    get "cities_select_area" => "users#cities_select_area"
    # ここまで

  resources :users, shallow: true do
    resources :reports, only: %[index]
  end

  resources :reports do
    collection do
      post :confirm
      get 'search'
    end
    member do
      patch :confirm
      patch :release
      patch :nonrelease
    end
    resource :likes, only: [:create, :destroy]
  end

  resources :clinics

  # centerの各レポコ下部のclinic, prefecture, cityのリンク↓
  get 'clinic/:value' => 'clinics#clinic_report'
  get 'clinics/region/:region' => 'clinics#region'
  get 'clinics_/:prefecture' => 'clinics#prefecture'
  get 'clinics/:prefecture/:value' => 'clinics#city'
  get 'search_cl' => 'clinics#search_cl'
  # ここまで

  # formでも利用
  get "cities_select" => "searches#cities_select_clinics"
  get "clinics_select" => "searches#clinics_select"
  # ここまで

  get "clinic_select" => "searches#clinic_select"

  get "address_cities_select" => "reports#address_cities_select"

  resources :comments, only: %i[create destroy]

  resources :notifications, only: :index

  namespace :admin do
    resources :users
    resources :reports
    resources :clinics
    root 'admin#home'
  end

  get "signup" => "reports#signup"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

# == Route Map
#
#                                Prefix Verb   URI Pattern                                                                              Controller#Action
#                                  root GET    /                                                                                        reports#index
#                               my_page GET    /my_page(.:format)                                                                       my_page#index
#                         my_page_draft GET    /my_page/draft(.:format)                                                                 reports#draft
#                                thanks GET    /thanks(.:format)                                                                        my_page#thanks
#                                search GET    /search(.:format)                                                                        searches#search
#                                   age GET    /age(.:format)                                                                           searches#all_age
#                                       GET    /age/:value(.:format)                                                                    searches#age
#                                   amh GET    /amh(.:format)                                                                           searches#all_amh
#                                       GET    /amh/:value(.:format)                                                                    searches#amh
#                                status GET    /status(.:format)                                                                        searches#all_status
#                                       GET    /status/:value(.:format)                                                                 searches#status
#                        search_clinics GET    /search/clinics(.:format)                                                                searches#clinics
#                 category_clinics_area GET    /category/clinics_area(.:format)                                                         searches#clinics_area
#                                       GET    /category/clinics_area/prefecture/:value(.:format)                                       searches#clinic_prefecture_area
#                                       GET    /category/clinics_area/city/:value(.:format)                                             searches#clinic_city_area
#                         category_tags GET    /category/tags(.:format)                                                                 searches#tags
#                                       GET    /:category/:tags/:gender/:value(.:format)                                                searches#tag
#                                 works GET    /works(.:format)                                                                         searches#works
#                                       GET    /work/:value(.:format)                                                                   searches#work
#                                 costs GET    /costs(.:format)                                                                         searches#costs
#                                       GET    /cost/:value(.:format)                                                                   searches#cost
#                                 about GET    /about(.:format)                                                                         application#about
#                                 terms GET    /terms(.:format)                                                                         application#terms
#                               privacy GET    /privacy(.:format)                                                                       application#privacy
#                             guideline GET    /guideline(.:format)                                                                     application#guideline
#                                repoco GET    /repoco(.:format)                                                                        application#repoco
#                           terminology GET    /terminology(.:format)                                                                   application#terminology
#                                   faq GET    /faq(.:format)                                                                           application#faq
#                                  make GET    /make(.:format)                                                                          application#make
#                                  hack GET    /hack(.:format)                                                                          application#hack
#                             statistic GET    /statistic(.:format)                                                                     application#statistic
#                      new_user_session GET    /sign_in(.:format)                                                                       users/sessions#new
#                          user_session POST   /sign_in(.:format)                                                                       users/sessions#create
#                  destroy_user_session DELETE /sign_out(.:format)                                                                      users/sessions#destroy
#                     new_user_password GET    /password/new(.:format)                                                                  users/passwords#new
#                    edit_user_password GET    /password/edit(.:format)                                                                 users/passwords#edit
#                         user_password PATCH  /password(.:format)                                                                      users/passwords#update
#                                       PUT    /password(.:format)                                                                      users/passwords#update

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::ApplicationController
  def show
    @report = Report.find(params[:id])
    
    @clinics = @report.itinerary_of_choosing_a_clinics.order(order_of_transfer: "desc")
    @clinics_exist = @clinics.map { |i| i[:clinic_id] }

    @unsuccessful_sairan_cycles = @report.unsuccessful_sairan_cycles.order(un_sairan_number: "asc")
    @unsuccessful_ishoku_cycles = @report.unsuccessful_ishoku_cycles.order(un_ishoku_number: "asc")

    @special_inspection_era = @report.special_inspections.where(name: 1)
    @special_inspection_emma = @report.special_inspections.where(name: 2)
    @special_inspection_alice = @report.special_inspections.where(name: 3)
    @special_inspection_trio = @report.special_inspections.where(name: 4)
    @special_inspection_erpeak = @report.special_inspections.where(name: 5)
    @special_inspection_hysteroscopy = @report.special_inspections.where(name: 6)
    @special_inspection_intrauterine_flora = @report.special_inspections.where(name: 7)
    @special_inspection_endometrial_biopsy = @report.special_inspections.where(name: 8)
    @special_inspection_hidukeshin = @report.special_inspections.where(name: 9)
    @special_inspection_bce = @report.special_inspections.where(name: 10)
    @special_inspection_chromosome = @report.special_inspections.where(name: 11)
    @special_inspection_ca125 = @report.special_inspections.where(name: 12)
    @special_inspection_mri = @report.special_inspections.where(name: 13)
    @special_inspection_vitamin_d = @report.special_inspections.where(name: 14)
    @special_inspection_copper_zinc = @report.special_inspections.where(name: 15)
    @special_inspection_kruger = @report.special_inspections.where(name: 16)
    @special_inspection_dfi = @report.special_inspections.where(name: 17)
    @special_inspection_pgta = @report.special_inspections.where(name: 18)
    @special_inspection_other_inspection = @report.special_inspections.where(name: 99)

    gon.clinic_name = @report.clinic.name
    gon.clinic_evaluation = []
    gon.clinic_evaluation << @report.doctor_quality << @report.staff_quality << @report.impression_of_technology << @report.impression_of_price << @report.average_waiting_time2 << @report.comfort_of_space
    @clinic_evaluation = gon.clinic_evaluation.compact

    if @report.doctor_quality.blank?
      @report.doctor_quality = 0
    end
    if @report.staff_quality.blank?
      @report.staff_quality = 0
    end
    if @report.impression_of_technology.blank?
      @report.impression_of_technology = 0
    end
    if @report.impression_of_price.blank?
      @report.impression_of_price = 0
    end
    if @report.average_waiting_time2.blank?
      @report.average_waiting_time2 = 0
    end
    if @report.comfort_of_space.blank?
      @report.comfort_of_space = 0
    end
    @average_score = ((@report.doctor_quality + @report.staff_quality + @report.impression_of_technology + @report.impression_of_price + @report.average_waiting_time2 + @report.comfort_of_space)/6.to_f).round(1)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_before_ishoku_hormone_fields.html.erb
<div class="nested-fields well well-compact">
  <table class="table table-sm table-bordered table-hover mb-0">
    <thead>
      <tr>
        <th scope="col" class="hormon-label text-center align-middle text-danger">Day</th>
        <th scope="col" class="hormon-label">E2</th>
        <th scope="col" class="hormon-label">FSH</th>
        <th scope="col" class="hormon-label">LH</th>
        <th scope="col" class="hormon-label">P4</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="day-column-before-ishoku-hormone"><%= f.select :day, Report.make_select_before_ishoku_hormone_day, { prompt: "必須選択" }, { class: "form-control text-muted" } %></th>
        <td class="hormon-column"><%= f.number_field :e2, { step: "0.01", class: "form-control", placeholder: "pg/ml" } %></td>
        <td class="hormon-column"><%= f.number_field :fsh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="hormon-column"><%= f.number_field :lh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="hormon-column"><%= f.number_field :p4, { step: "0.01", class: "form-control", placeholder: "ng/ml" } %></td>
      </tr>
    </tbody>
  </table>
  <small class="float-right pr-2 mt-2 mb-3">
    <%= link_to_remove_association "削除", f, class: "text-secondary" %>
  </small>
</div>

app/views/reports/_category_header.html.erb
<div class="container mt-3 category-header-list">
  <div class="p-0 text-center">
      <%= link_to search_path do %>
        <button type="button" class="btn text-muted rounded-pill">＼ <i data-feather="arrow-down" class="px-1 mb-1"></i>カテゴリからレポコを検索 <i data-feather="arrow-down" class="px-1 mb-1"></i>／</button>
      <% end %>
    <br>
    <%= render 'category_header_body' %>
  </div>
</div>

app/views/reports/_haibanhoishoku_hormone_fields.html.erb
<div class="nested-fields well well-compact">
  <table class="table table-sm table-bordered table-hover mb-0">
    <thead>
      <tr>
        <th scope="col" class="hormon-label text-center align-middle text-danger">ET･BT</th>
        <th scope="col" class="hormon-label">E2</th>
        <th scope="col" class="hormon-label">FSH</th>
        <th scope="col" class="hormon-label">LH</th>
        <th scope="col" class="hormon-label">P4</th>
        <th scope="col" class="hormon-label">hCG</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="day-column-et-bt"><%= f.select :bt, Report.make_select_haibanhoishoku_hormone_day, { prompt: "必須選択" }, { class: "form-control text-muted" } %></th>
        <td class="et-bt-hormone-column"><%= f.number_field :e2, { step: "0.01", class: "form-control", placeholder: "pg/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :fsh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :lh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :p4, { step: "0.01", class: "form-control", placeholder: "ng/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :hcg, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
      </tr>
    </tbody>
  </table>
  <small class="float-right pr-2 mt-2 mb-3">
    <%= link_to_remove_association "削除", f, class: "text-secondary" %>
  </small>
</div>

app/views/reports/_itinerary_of_choosing_a_clinic_fields.html.erb
<div class="nested-fields well well-compact mb-0">
  <table class="table table-sm table-bordered table-hover mb-0">
    <thead>
      <tr>
        <th scope="col" class="itinerary-of-clinic-label itinerary-of-clinic-col1 text-center align-middle">順</th>
        <th scope="col" class="itinerary-of-clinic-label itinerary-of-clinic-col2 text-center align-middle"><small>都道府県</small></th>
        <th scope="col" class="itinerary-of-clinic-label itinerary-of-clinic-col3 text-center align-middle">クリニック</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-center align-middle"><%= f.select :order_of_transfer, Report.make_select_itinerary_of_choosing_a_clinics_order_of_transfer.invert, { prompt: "① →" }, { class: "form-control text-muted" } %></td>
        <td class="text-center align-middle">
          <% if f.object.clinic.blank? %>
            <% prefecture_id = nil %>
          <% else %>
            <% prefecture_id = f.object.clinic.prefecture_id %>
          <% end %>
          <%= select_tag :clinic_prefecture,
                          options_from_collection_for_select(Prefecture.where(id: 1..47), :id, :name, selected: prefecture_id),
                          {
                            prompt: "② →",
                            class: "form-control clinic_prefecture"
                          }
          %>
        </td>
        <td class="text-center align-middle">
          <% if f.object.clinic.blank? %>
            <%= f.select :clinic_id, {}, { prompt: "③"}, { class: "form-control itinerary_of_clinic" } %>
          <% else %>
            <% clinics = Clinic.where(prefecture_id: prefecture_id).order(id: "ASC") %>
            <% options = {} %>
            <% clinics.each do |clinic| %>
              <% options[clinic.name] = clinic.id %>
            <% end %>
            <%= f.select :clinic_id, options, {prompt: "③"}, { class: "form-control" } %>
          <% end %>
        </td>

        <script>
          $(function() {
            $('.clinic_prefecture').change(function() {
              let clinic = $(this).parent().next().children("select");
              $.ajax('/clinic_select',
                {
                  type: 'get',
                  data: { prefecture_id: $(this).val() },
                }
              )
              .done(function(data) {
                clinic.html(data) 
              })
              .fail(function() {
                window.alert('正しい結果を得られませんでした。');
              });
            });
          });
        </script>
        
      </tr>
    </tbody>
  </table>
  <div class="d-flex justify-content-end align-items-center">
    <small id="poster-tip" class="form-text text-muted text-right m-0 mr-4 pt-2 pb-2">
      <%= f.check_box :public_status, {}, "hide", "show" %>&nbsp;非公開
    </small>
    <div class="m-0 pt-2 pb-2 pr-2">
      <%= link_to_remove_association "削除", f, class: "text-secondary" %>
    </div>
  </div>
</div>

app/views/reports/_left.html.erb
<h3 class="mt-4">注目レポコ</h3>
<div class="side-ranking">
  
  <ul class="nav nav-tabs" id="side-access-ranking-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="side-weekly-ranking-tab" data-toggle="tab" href="#side-weekly-ranking" role="tab" aria-controls="side-weekly-ranking" aria-selected="true">Weekly</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="side-monthly-ranking-tab" data-toggle="tab" href="#side-monthly-ranking" role="tab" aria-controls="side-monthly-ranking" aria-selected="false">Monthly</a>
    </li>
  </ul>

  <div class="tab-content" id="side-access-ranking">

    <div class="tab-pane fade show active" id="side-weekly-ranking" role="tabpanel" aria-labelledby="side-weekly-ranking-tab">
      <p>記事リンクで囲む
        <div class="card mb-2">
          <img class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">タイトル</h5>
              <p class="card-text">
                #タグ
              </p>
          </div>
        </div>
      </p>
    
    </div>

    <div class="tab-pane fade" id="side-monthly-ranking" role="tabpanel" aria-labelledby="side-monthly-ranking-tab">
      <p>記事リンクで囲む
        <div class="card mb-2">
          <img class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">タイトル</h5>
              <p class="card-text">
                #タグ
              </p>
          </div>
        </div>
      </p>
    </div>
  
  </div>
</div>

app/views/reports/_shokihaiishoku_hormone_fields.html.erb
<div class="nested-fields well well-compact">
  <table class="table table-sm table-bordered table-hover mb-0">
    <thead>
      <tr>
        <th scope="col" class="hormon-label text-center align-middle">ET</th>
        <th scope="col" class="hormon-label">hCG</th>
        <th scope="col" class="hormon-label">E2</th>
        <th scope="col" class="hormon-label">FSH</th>
        <th scope="col" class="hormon-label">LH</th>
        <th scope="col" class="hormon-label">P4</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row" class="et-bt-column"><%= f.select :et, Report.make_select_shokihaiishoku_hormone_day, { prompt: "選択" }, { class: "form-control text-muted" } %></th>
        <td class="et-bt-hormone-column"><%= f.number_field :hcg, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :e2, { step: "0.01", class: "form-control", placeholder: "pg/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :fsh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :lh, { step: "0.01", class: "form-control", placeholder: "mIU/ml" } %></td>
        <td class="et-bt-hormone-column"><%= f.number_field :p4, { step: "0.01", class: "form-control", placeholder: "ng/ml" } %></td>
      </tr>
    </tbody>
  </table>
  <small class="float-right pr-2">
    <%= link_to_remove_association "削除", f, class: "text-secondary" %>
  </small>
</div>

app/views/reports/_special_inspection_fields.html.erb
<div class="nested-fields well well-compact">
  <table class="table table-sm table-hover table-bordered mb-0 special_inspections_table table_radius">
    <tr>
      <td class="hormon-label text-center align-middle px-0 small rounded-lg border-right" style="background: #ffffff;">検査名</td>
      <td class="hormon-label text-center small rounded-lg" style="background: #ffffff;">受診</td>
    </tr>
    <tr>
      <td scope="row" class="et-bt-column border-right"><%= f.select :name, SpecialInspection::HASH_SPECIAL_INSPECTION_NAME.invert, { prompt: "" }, { class: "form-control text-muted" } %></td>
      <td class="et-bt-hormone-column"><%= f.select :place, SpecialInspection::HASH_SPECIAL_INSPECTION_PLACE.invert, { prompt: "" }, { class: "form-control text-muted" } %></td>
    </tr>
  </table>
  <small class="float-right pr-2 mt-2">
    <%= link_to_remove_association "削除", f, class: "text-secondary" %>
  </small>
</div>
<%= javascript_include_tag 'report_show' %>

app/views/reports/_unsuccessful_sairan_cycle_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="m-0">
  &nbsp;
  <div>
  <div class="box27 px-1 mb-0">
    <span class="box-title">採卵1サイクル</span>
    <table class="table table-sm table-bordered table-hover mb-0">
      <tbody>
        <tr>
          <td>
            <small class="text-muted">何回目の採卵？</small>
            <%= f.select :un_sairan_number, UnsuccessfulSairanCycle::HASH_NUMBER_OF_SAIRAN.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">↑  採卵時の年齢</small>
            <%= f.select :un_sairan_age, UnsuccessfulSairanCycle::HASH_SAIRAN_AGE.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">誘発タイプ</small>
            <%= f.select :un_sairan_type_of_ovarian_stimulation, UnsuccessfulSairanCycle::HASH_TYPE_OF_OVARIAN_STIMULATION.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">採卵個数</small>
            <%= f.select :un_sairan_number_of_eggs_collected, UnsuccessfulSairanCycle::HASH_NUMBER_OF_EGGS.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">受精個数</small>
            <%= f.select :un_sairan_number_of_fertilized_eggs, UnsuccessfulSairanCycle::HASH_NUMBER_OF_EGGS.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">移植可能胚数(新鮮胚含む)</small>
            <%= f.select :un_sairan_number_of_transferable_embryos, UnsuccessfulSairanCycle::HASH_NUMBER_OF_EGGS.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">そのうちの凍結胚数</small>
            <%= f.select :un_sairan_number_of_frozen_eggs, UnsuccessfulSairanCycle::HASH_NUMBER_OF_EGGS.invert, { prompt: "" }, { class: "form-control py-0" } %>
          </td>
        </tr>
        <tr>
          <td>
            <small class="text-muted">メモ</small>
            <%= f.text_area :un_sairan_memo, class: "form-control p-2 border rounded-lg", style: "background: rgb(232, 254, 252); line-height: 1.5; font-size: 13px;", rows: 5, placeholder: "" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <small class="float-right pr-2 mt-1">
    <%= link_to_remove_association "削除", f, class: "text-secondary" %>
  </small>
</div>

app/views/reports/draft.html.erb
<h3 class="d-none d-md-block mt-4 mb-4">下書きレポコ</h3>
<h3 class="d-sm d-md-none mt-4 mb-4 text-center">下書きレポコ</h3>

<div class="container m-bottom">
  <div class="row reports-index">
    <% @reports.each do |report| %>
      <div class="report-box col-xs-12 col-sm-12 col-md-6 col-lg-4 my-2">
        <div class="report-box-inner mx-0.1 px-3 py-3 h-100 rounded border">
          <%= link_to report do %>
          <div class="report-body h-50">
            <h5 class="report-title text-dark"><%= report.title %></h5>
            <div class="row">
              <div class="tag-box col-xs-4 col-sm-4 col-md-3">
              
              </div>
            </div>
          </div>
          <% end %>
          <div class="report-info border-top">
            <div class="row">
              <div class="report-icon col-3">
                <%= report.user.icon %>
              </div>
              <div class="report-author col-9">
                <div><%= link_to report.user.name, user_path(report.user_id) %></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reports/new.html.erb
<% if false %>
  <div class="row show">
    <div class="col-md-2"></div>
    <div class="col-md-8 d-flex align-items-center">
      <h1>レポコ作成</h1>
      <div class="ml-auto posts_button">
        <%= link_to "レポコ一覧", reports_path, class:"btn btn-outline-info" %>
      </div>
    </div>
  </div>
<% end %>

<%= render 'form', report: @report, is_new: true %><br>

app/views/reports/signup.html.erb
<div class="container signup-in m-bottom">
    <div class="row">
      <div class="col-md-6 offset-md-3 mt-md-5 mb-md-5">
        <div class="text-center pt-5 pb-3">
          <h3><i data-feather="chevron-right" class="pb-1"></i><%= link_to "レポコ一覧ページ", root_path %></h3>
        </div>
        <div class="card text-center mt-4">
          <div class="pt-4">
            <h3 class="mb-0 text-dark font-weight-bold">Sign Up</h3>
          </div>
          <div class="card-body pt-0">
            <div class="pt-0">
              <p class="pt-5 mb-1 text-left">体外･顕微授精にて妊娠･出産された方で投稿して頂ける場合には、お手数おかけして恐縮ですが以下twitterへDM、またはメールアドレスまでご連絡ください。</p>
              <p class="mb-3 text-left">登録URLをお送りさせていただきます&nbsp;↓</p>
              <div class="popup_area">
                <%= link_to "https://twitter.com/repoco_official", {class: "text-decoration-none w-100", target: :_blank, rel: "noopener noreferrer"} do %>
                  <button class="tw_blue_btn p-1"><%= image_tag"action/Twitter_Social_Icon_Rounded_Square_Color.svg", width: "35px", class: "img-fluid", loading: "lazy" %>REPOCO_OFFICIAL</button>
                <% end %>
              </div>
              <div class="popup_area mt-4">
                <center><button class="btn btn-outline-primary btn-raised w-100 img-fluid"><a href="mailto:repoco.net@gmail.com?subject=レポコの投稿について&amp;body=（自動スパムメールなどへの対策・判別のため、お手数おかけしますが、空メールではなく本文に簡単にメッセージを添えていただけると幸いです。）">Eメールはこちらから</a>&nbsp;<i data-feather="send" class="feather-icon-style1"></i></button></center>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>